### ISSUE TITLE
Interfaces documentation

### ISSUE THREAD

**Issue by lsc36** [ntucllab/libact#10]

**Comment by tungen** [comment]
@lsc36 @yangarbiter can you identify us which interfaces we can help add documents to? Thanks.

**Comment by lsc36** [comment]
Those in `libact/base/interfaces.py`. Thanks.

**Comment by tungen** [comment]
I've finish a first version of it. Please help check for any style/content problems. Thanks. @lsc36, @yangarbiter

**Comment by lsc36** [comment]
Did you push your changes?

**Comment by yangarbiter** [comment]
He push it in master

**Comment by tungen** [comment]
I pushed to master because only the #TODO... parts are modified and no execution codes are added/modified. Apologize for not following the standard workflow...

**Comment by lsc36** [comment]
Sorry I just didn't saw it. That's OK.

**Comment by lsc36** [comment]
I'd prefer adding docs for class methods, especially those for QS and Model explaining:

- that `QS.update` updates internal state and `QS.make_query` is read-only
- the return value of `Model.predict_real`
