### ISSUE TITLE
Incompatibility with plotly and cufflinks

### ISSUE THREAD

**Issue by tsabata** [ntucllab/libact#112]
Hello,
I have found that your lib is not compatible with python packages _plotly_ and _cufflinks_. I have tested it on fresh install of ubuntu 16.04 where anaconda was installed.
Everything was ok till installation of plotly and cufflinks:
```

pip install plotly --upgrade
pip install cufflinks --upgrade
```
Then running python setup.py test ends on this:

```
======================================================================
ERROR: query_strategies (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: query_strategies
Traceback (most recent call last):
  File "/path/anaconda3/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/path/libact/libact/query_strategies/__init__.py", line 20, in <module>
    from ._variance_reduction import estVar
ImportError: /usr/lib/liblapacke.so.3: undefined symbol: dpotrf2_

```

**Comment by yangarbiter** [comment]
It seems like it is the problem explained here:
http://stackoverflow.com/questions/8917977/installing-lapack-for-numpy

**Comment by tsabata** [comment]
OK I find a solution in combination of two problems, if you have same problem do the following:

`sudo apt-get remove libatlas3-base`
It gives you different error durring test:
`Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.`

This can be solved by:

```
conda install  -f  numpy
conda install mkl
```

>
