### ISSUE TITLE
Probabilistic models 

### ISSUE THREAD

**Issue by stkarlos** [ntucllab/libact#117]
I would like to ask you about which classsifiers are theorized as Probabilistic so as to be combined with query strategies like Uncertainty Sampling?

Thanks in advance.

**Comment by chkoar** [comment]
@stkarlos  in terms of `libact` API, a probabilistic model is any classifier that inherits from `ProbabilisticModel`, implements the `predict_proba` method and outputs class membership probabilities. The `UncertaintySampling` strategy expects a model that derives from `ProbabilisticModel` or `ContinuousModel` and implements a `predict_proba` method and a `predict_real`, respectively. Currently in `libact` there is a `libact.models.logistic_regression.LogisticRegression` model that inherits from the `ProbabilisticModel` and implements the `predict_proba` method. Apart from that you could use any `scikit-learn` API compatible classifier that implements the `predict_proba` method using the `SklearnProbaAdapter`.

Check  [this](http://libact.readthedocs.io/en/latest/libact.models.html#libact.models.sklearn_adapter.SklearnProbaAdapter) code example  out.

**Comment by yangarbiter** [comment]
Maybe [this article](http://scikit-learn.org/stable/modules/calibration.html) can help you understand better about the difference between predict_real and predict_proba.

LogisticRegression is the most natural classifier to be taken as Probabilistic.
While other classifier should be able to be used if you use calibrators like the 
[CalibratedClassifierCV in sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.calibration.CalibratedClassifierCV.html#sklearn.calibration.CalibratedClassifierCV) to implement predict_proba.

**Comment by yangarbiter** [comment]
It seems this issues is solved for now.
