### ISSUE TITLE
Backport to Python 2

### ISSUE THREAD

**Issue by lsc36** [ntucllab/libact#12]

**Comment by yonilx** [comment]
any updates on the backport ?

**Comment by yangarbiter** [comment]
I am currently working on it.

**Comment by yangarbiter** [comment]
@yonilx, I have drafted some possible solution for this issue on this branch
https://github.com/ntucllab/libact/tree/backport2

Since we might have to take some time to review over the code, you may use the code on this branch first. Also feel free to give us comments.

Thanks.

**Comment by yangarbiter** [comment]
We've merged the backport branch into master, it should support python2 now.

**Comment by yonilx** [comment]
Thanks ! You guys are awesome !
