### ISSUE TITLE
I encountered an error when I installed libact.

### ISSUE THREAD

**Issue by souvenir13** [ntucllab/libact#125]
running on Python 3.6.1 :: Anaconda 4.4.0 (64-bit) on Win8.1

![20170810001543](https://user-images.githubusercontent.com/16315066/29132001-4d8948f0-7d61-11e7-8a4a-9f481ec42928.png)

![20170810001641](https://user-images.githubusercontent.com/16315066/29131961-2413ff4c-7d61-11e7-8761-410b758b23b3.png)

I have already installed VS2015 and set the environment variable, but the error still be here. 
I set the Path = "F:\Program\Microsoft Visual Studio 14.0\VC\bin;"
             VS140COMNTOOLS = "F:\Program\Microsoft Visual Studio 14.0\Common7\Tools\"
             INCLUDE="C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt"

anything else should I do ? and why does this happened ? 
Thanks for watching and appreciate for your help!!!!

**Comment by yangarbiter** [comment]
I am not entirely sure about the problem, but I googled it and found something may that be helpful.

https://stackoverflow.com/questions/39771592/visual-c-for-python-failed-with-exit-status-2-when-installing-divisi2

https://stackoverflow.com/questions/39358876/visual-c-for-python-failed-with-exit-status-2
