### ISSUE TITLE
Only about suggestion/example download data

### ISSUE THREAD

**Issue by MrLevo520** [ntucllab/libact#127]
Not everyone use python3, so in EXAMPLE the get_datasets not work for python2, it's easy to   handle it but as an example, i think it will be better if the datasets already there !
btw, i think the project is awesome!

**Comment by yangarbiter** [comment]
I've quickly fixed it with this commit https://github.com/ntucllab/libact/commit/5a6bc98d01ad36fdf3f54cc6c341faf821d475fe

Thank you for reporting.
