### ISSUE TITLE
Error installing on Mac OS

### ISSUE THREAD

**Issue by ukamath** [ntucllab/libact#130]
building 'libact.query_strategies._variance_reduction' extension
    C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/uday.kamath/anaconda/include -arch x86_64 -I/Users/uday.kamath/anaconda/include -arch x86_64
    
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/libact
    creating build/temp.macosx-10.7-x86_64-3.6/libact/query_strategies
    creating build/temp.macosx-10.7-x86_64-3.6/libact/query_strategies/src
    creating build/temp.macosx-10.7-x86_64-3.6/libact/query_strategies/src/variance_reduction
    compile options: '-I/Users/uday.kamath/anaconda/lib/python3.6/site-packages/numpy/core/include -I/usr/local/opt/openblas/include -I/Users/uday.kamath/anaconda/include/python3.6m -c'
    extra options: '-std=c11'
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    gcc: libact/query_strategies/src/variance_reduction/variance_reduction.c
    libact/query_strategies/src/variance_reduction/variance_reduction.c:5:10: fatal error: 'lapacke.h' file not found
    #include <lapacke.h>
             ^
    1 error generated.
    libact/query_strategies/src/variance_reduction/variance_reduction.c:5:10: fatal error: 'lapacke.h' file not found
    #include <lapacke.h>
             ^
    1 error generated.
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/uday.kamath/anaconda/include -arch x86_64 -I/Users/uday.kamath/anaconda/include -arch x86_64 -I/Users/uday.kamath/anaconda/lib/python3.6/site-packages/numpy/core/include -I/usr/local/opt/openblas/include -I/Users/uday.kamath/anaconda/include/python3.6m -c libact/query_strategies/src/variance_reduction/variance_reduction.c -o build/temp.macosx-10.7-x86_64-3.6/libact/query_strategies/src/variance_reduction/variance_reduction.o -std=c11" failed with exit status 1
    
    ----------------------------------------
Command "/Users/uday.kamath/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/qv/01jf6kd93lgff92l9gdkhgcw0000gp/T/pip-67kcdjfp-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/qv/01jf6kd93lgff92l9gdkhgcw0000gp/T/pip-k40dk3ws-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/qv/01jf6kd93lgff92l9gdkhgcw0000gp/T/pip-67kcdjfp-build/

**Comment by skgg** [comment]
Please refer to "Basic Dependencies" section in README to install openblas on macOS.

**Comment by ukamath** [comment]
I installed OpenBlas
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j 8 -f Makefile.install install
Generating openblas_config.h in /opt/X11/include
Generating f77blas.h in /opt/X11/include
Generating cblas.h in /opt/X11/include
Copying the static library to /opt/X11/lib
Copying the shared library to /opt/X11/lib
Generating openblas.pc in /opt/X11/lib/pkgconfig
Generating OpenBLASConfig.cmake in /opt/X11/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /opt/X11/lib/cmake/openblas
Install OK!

*************************
My path is 
/Users/uday.kamath/anaconda/bin:/Users/uday.kamath/anaconda/bin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

******************************

Let me know

**Comment by ukamath** [comment]
Resolved. Thanks

**Comment by tsiakmaki** [comment]
in my catalina macos worked the above: 

```
brew install openblas

export LDFLAGS="-L/usr/local/Cellar/openblas/0.3.7/lib"
export CPPFLAGS="-I/usr/local/Cellar/openblas/0.3.7/include"
export PKG_CONFIG_PATH="/usr/local/Cellar/openblas/0.3.7/lib/pkgconfig"
export CPATH=/usr/local/Cellar/openblas/0.3.7/include
```
thank you for your contribution.
