### ISSUE TITLE
Error while installing the package on windows 10

### ISSUE THREAD

**Issue by Jewgether** [ntucllab/libact#141]
Hello, 
I am using python 3.6, on windows 10 (64 bit).
I have installed all the requirements well, and when I tried to install libact, I get the following (the error is in bold below). 

Any idea what should I do? 

Collecting libact
  Using cached https://files.pythonhosted.org/packages/16/eb/2f649f4115d75076b7d09d0db0d6eb2696509a7de0480e0d899ead0d3119/libact-0.1.3.tar.gz
Requirement already satisfied: numpy in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (1.14.3)
Requirement already satisfied: scipy in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (1.1.0)
Requirement already satisfied: scikit-learn in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (0.19.1)
Requirement already satisfied: Cython in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (0.28.2)
Requirement already satisfied: joblib in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (0.11)
Requirement already satisfied: six in c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages (from libact) (1.11.0)
Installing collected packages: libact
  Running setup.py install for libact ... error
    Complete output from command c:\users\tamir\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Tamir\\AppData\\Local\\Temp\\pip-install-tqhqcnod\\libact\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Tamir\AppData\Local\Temp\pip-record-oa1777u9\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Platform Detection: Linux. Link to liblapacke...
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\libact
    copying libact\__init__.py -> build\lib.win-amd64-3.6\libact
    creating build\lib.win-amd64-3.6\libact\base
    copying libact\base\dataset.py -> build\lib.win-amd64-3.6\libact\base
    copying libact\base\interfaces.py -> build\lib.win-amd64-3.6\libact\base
    copying libact\base\__init__.py -> build\lib.win-amd64-3.6\libact\base
    creating build\lib.win-amd64-3.6\libact\models
    copying libact\models\logistic_regression.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\perceptron.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\sklearn_adapter.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\svm.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\__init__.py -> build\lib.win-amd64-3.6\libact\models
    creating build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\binary_relevance.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\dummy_clf.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    creating build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\ideal_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\interactive_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\__init__.py -> build\lib.win-amd64-3.6\libact\labelers
    creating build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\active_learning_by_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\density_weighted_uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\hintsvm.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\query_by_committee.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\quire.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\random_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\variance_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies
    creating build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\adaptive_active_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\binary_minimization.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\maximum_margin_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\multilabel_with_auxiliary_learner.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    creating build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\active_learning_with_cost_embedding.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\expected_error_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\hierarchical_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\mdsp.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    creating build\lib.win-amd64-3.6\libact\utils
    copying libact\utils\__init__.py -> build\lib.win-amd64-3.6\libact\utils
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'libact.query_strategies._variance_reduction' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\libact
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src\variance_reduction
    e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tamir\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\tamir\appdata\local\programs\python\python36\include -Ic:\users\tamir\appdata\local\programs\python\python36\include -I"e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" -I"e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11
    cl : Command line warning D9002 : ignoring unknown option '-std=c11'
    variance_reduction.c
    libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
    error: Command "e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tamir\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\tamir\appdata\local\programs\python\python36\include -Ic:\users\tamir\appdata\local\programs\python\python36\include -I"e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" -I"e:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11" failed with exit status 2

    **----------------------------------------
**Command "c:\users\tamir\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Tamir\\AppData\\Local\\Temp\\pip-install-tqhqcnod\\libact\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Tamir\AppData\Local\Temp\pip-record-oa1777u9\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\Tamir\AppData\Local\Temp\pip-install-tqhqcnod\libact\****

Thanks, 
Tamir

**Comment by yangarbiter** [comment]
libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory

It seems you are missing the lapacke package.

**Comment by yangarbiter** [comment]
#118
