### ISSUE TITLE
SVM: use scikit-learn instead of LIBSVM

### ISSUE THREAD

**Issue by lsc36** [ntucllab/libact#15]
Separate changes out from `quire` branch.

**Comment by yangarbiter** [comment]
One thing to be concern is that changing from LIBSVM to scikit-learn is that scikit-learn only has the interface for predict_proba, which will take relatively long to train in compare with calculating the distance to margin (which predict_real only needs).

@hsuantien 
Should we still switch scikit-learn or I should just try to calculate the margin with primal coefficient?

**Comment by hsuantien** [comment]
From scikit-learn document

The SVC
<http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC>
 method decision_function gives per-class scores for each sample (or a
single score per sample in the binary case).

So I think it is possible to just connect our predict_real to
decision_function?

Thanks.

--HT


On Wed, Dec 16, 2015 at 1:28 PM, yangarbiter <notifications@github.com>
wrote:

> One thing to be concern is that changing from LIBSVM to scikit-learn is
> that scikit-learn only has the interface for predict_proba, which will take
> relatively long to train in compare with calculating the distance to margin
> (which predict_real only needs).
>
> @hsuantien <https://github.com/hsuantien>
> Should we still switch scikit-learn or I should just try to calculate the
> margin with primal coefficient?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntucllab/libact/issues/15#issuecomment-164998494>.
>



-- 
--------------------------------------------------------------------------------
Hsuan-Tien Lin         htlin@csie.ntu.edu.tw
http://www.csie.ntu.edu.tw/~htlin
==========
Associate Professor
Dept. of Computer Science and Information Engineering
& Graduate Institute of Networking and Multimedia
National Taiwan University
--------------------------------------------------------------------------------

**Comment by yangarbiter** [comment]
I've also change logistic_regression's predict_prob to decision_function too.

**Comment by lsc36** [comment]
Will this affect the outcome of QSs?

**Comment by yangarbiter** [comment]
For uncertainty sampling, theoretically it would only affect the method least entropy (which I took it out int #1)

**Comment by lsc36** [comment]
#19 merged. Please refer to #21 for the predict_real issue.
