### ISSUE TITLE
libact on colab

### ISSUE THREAD

**Issue by terry07** [ntucllab/libact#151]
Hello everyone,

i would like to ask if a proper installation of libact on colab platform is feasible?

Thanks for your help.

**Comment by chkoar** [comment]
In general you can install packages using the command `!pip install package_name` from a code cell. Assuming that you  have already install the libact dependencies you could try `!pip install libact`.

**Comment by yangarbiter** [comment]
I am able to install it with these commands

```
!apt-get install build-essential gfortran libatlas-base-dev liblapacke-dev python3-dev
!pip --no-cache-dir install Cython
!pip --no-cache-dir install libact
```
