### ISSUE TITLE
Have trouble to install libact on windows. 

### ISSUE THREAD

**Issue by ysforgithub** [ntucllab/libact#157]

**Comment by ysforgithub** [comment]
Have tried pip install libact and conda install libact. 
Before I got an error regarding the c++ video tool. then I installed the 2017 video studio building tool. 
But I got these following error when trying to install libact:
Collecting git+https://github.com/ntucllab/libact.git
  Cloning https://github.com/ntucllab/libact.git to c:\users\syang\appdata\local\temp\pip-req-build-uz2d716r
Requirement already satisfied: numpy in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (1.14.2)
Requirement already satisfied: scipy in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (1.1.0)
Requirement already satisfied: scikit-learn in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (0.19.1)
Requirement already satisfied: Cython in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (0.27.3)
Requirement already satisfied: joblib in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (0.13.2)
Requirement already satisfied: six in c:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages (from libact==0.1.3) (1.11.0)
Building wheels for collected packages: libact
  Building wheel for libact (setup.py) ... error
  Complete output from command c:\users\syang\appdata\local\continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\syang\\AppData\\Local\\Temp\\pip-req-build-uz2d716r\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\syang\AppData\Local\Temp\pip-wheel-ojci59wa --python-tag cp36:
  Platform Detection: Linux. Link to liblapacke...
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\libact
  copying libact\__init__.py -> build\lib.win-amd64-3.6\libact
  creating build\lib.win-amd64-3.6\libact\base
  copying libact\base\dataset.py -> build\lib.win-amd64-3.6\libact\base
  copying libact\base\interfaces.py -> build\lib.win-amd64-3.6\libact\base
  copying libact\base\__init__.py -> build\lib.win-amd64-3.6\libact\base
  creating build\lib.win-amd64-3.6\libact\models
  copying libact\models\logistic_regression.py -> build\lib.win-amd64-3.6\libact\models
  copying libact\models\perceptron.py -> build\lib.win-amd64-3.6\libact\models
  copying libact\models\sklearn_adapter.py -> build\lib.win-amd64-3.6\libact\models
  copying libact\models\svm.py -> build\lib.win-amd64-3.6\libact\models
  copying libact\models\__init__.py -> build\lib.win-amd64-3.6\libact\models
  creating build\lib.win-amd64-3.6\libact\models\multilabel
  copying libact\models\multilabel\binary_relevance.py -> build\lib.win-amd64-3.6\libact\models\multilabel
  copying libact\models\multilabel\dummy_clf.py -> build\lib.win-amd64-3.6\libact\models\multilabel
  copying libact\models\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\models\multilabel
  creating build\lib.win-amd64-3.6\libact\labelers
  copying libact\labelers\ideal_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
  copying libact\labelers\interactive_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
  copying libact\labelers\__init__.py -> build\lib.win-amd64-3.6\libact\labelers
  creating build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\active_learning_by_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\density_weighted_uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\hintsvm.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\query_by_committee.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\quire.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\random_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\variance_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies
  copying libact\query_strategies\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies
  creating build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\adaptive_active_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\binary_minimization.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\maximum_margin_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\multilabel_with_auxiliary_learner.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
  creating build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\active_learning_with_cost_embedding.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\expected_error_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\hierarchical_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\mdsp.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
  creating build\lib.win-amd64-3.6\libact\utils
  copying libact\utils\__init__.py -> build\lib.win-amd64-3.6\libact\utils
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  building 'libact.query_strategies._variance_reduction' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\libact
  creating build\temp.win-amd64-3.6\Release\libact\query_strategies
  creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src
  creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src\variance_reduction
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\syang\appdata\local\continuum\anaconda3\include -Ic:\users\syang\appdata\local\continuum\anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11
  cl : Command line warning D9002 : ignoring unknown option '-std=c11'
  variance_reduction.c
  libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\syang\appdata\local\continuum\anaconda3\include -Ic:\users\syang\appdata\local\continuum\anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11" failed with exit status 2

  ----------------------------------------
  Failed building wheel for libact
  Running setup.py clean for libact
Failed to build libact
Installing collected packages: libact
  Running setup.py install for libact ... error
    Complete output from command c:\users\syang\appdata\local\continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\syang\\AppData\\Local\\Temp\\pip-req-build-uz2d716r\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\syang\AppData\Local\Temp\pip-record-3bz38grr\install-record.txt --single-version-externally-managed --compile:
    Platform Detection: Linux. Link to liblapacke...
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\libact
    copying libact\__init__.py -> build\lib.win-amd64-3.6\libact
    creating build\lib.win-amd64-3.6\libact\base
    copying libact\base\dataset.py -> build\lib.win-amd64-3.6\libact\base
    copying libact\base\interfaces.py -> build\lib.win-amd64-3.6\libact\base
    copying libact\base\__init__.py -> build\lib.win-amd64-3.6\libact\base
    creating build\lib.win-amd64-3.6\libact\models
    copying libact\models\logistic_regression.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\perceptron.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\sklearn_adapter.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\svm.py -> build\lib.win-amd64-3.6\libact\models
    copying libact\models\__init__.py -> build\lib.win-amd64-3.6\libact\models
    creating build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\binary_relevance.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\dummy_clf.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    copying libact\models\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\models\multilabel
    creating build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\ideal_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\interactive_labeler.py -> build\lib.win-amd64-3.6\libact\labelers
    copying libact\labelers\__init__.py -> build\lib.win-amd64-3.6\libact\labelers
    creating build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\active_learning_by_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\density_weighted_uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\hintsvm.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\query_by_committee.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\quire.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\random_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\uncertainty_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\variance_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies
    copying libact\query_strategies\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies
    creating build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\adaptive_active_learning.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\binary_minimization.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\maximum_margin_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\multilabel_with_auxiliary_learner.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multilabel
    creating build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\active_learning_with_cost_embedding.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\expected_error_reduction.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\hierarchical_sampling.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\mdsp.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\__init__.py -> build\lib.win-amd64-3.6\libact\query_strategies\multiclass
    creating build\lib.win-amd64-3.6\libact\utils
    copying libact\utils\__init__.py -> build\lib.win-amd64-3.6\libact\utils
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'libact.query_strategies._variance_reduction' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\libact
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src
    creating build\temp.win-amd64-3.6\Release\libact\query_strategies\src\variance_reduction
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\syang\appdata\local\continuum\anaconda3\include -Ic:\users\syang\appdata\local\continuum\anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11
    cl : Command line warning D9002 : ignoring unknown option '-std=c11'
    variance_reduction.c
    libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\syang\appdata\local\continuum\anaconda3\lib\site-packages\numpy\core\include -I/usr/include/lapacke -Ic:\users\syang\appdata\local\continuum\anaconda3\include -Ic:\users\syang\appdata\local\continuum\anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.6\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11" failed with exit status 2

    ----------------------------------------
Command "c:\users\syang\appdata\local\continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\syang\\AppData\\Local\\Temp\\pip-req-build-uz2d716r\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\syang\AppData\Local\Temp\pip-record-3bz38grr\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\syang\AppData\Local\Temp\pip-req-build-uz2d716r\

**Comment by yangarbiter** [comment]
```
libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
```

This should be becuase you didn't install lapacke on your computer.

**Comment by wxl112** [comment]
hey guys, I run into the exact same problem.Have you got your problem fixed?I am waiting your reply

**Comment by hsuantien** [comment]
close this and merging with #175
