### ISSUE TITLE
centos installation

### ISSUE THREAD

**Issue by tsiakmaki** [ntucllab/libact#173]
could you please update the Dependencies for a Centos installation?

**Comment by hsuantien** [comment]
We do not have a Centos environment on hand to test. Any suggestions on what we should include?

**Comment by tsiakmaki** [comment]
finally, we set it up by installing: 
```
gcc/9.2.0 netlib-lapack/3.8.0 openblas
```
we also set the SPATH variable to include the location of the `lapacke.h`.
