### ISSUE TITLE
multilabel_plot.py  Error

### ISSUE THREAD

**Issue by TingNLP** [ntucllab/libact#176]
![1](https://user-images.githubusercontent.com/54096137/83244760-55a06300-a1d2-11ea-9e91-2cfe0c87a3a9.png)

**lb = lbr.label(X)**
It's work for running **multi-class** because we have only one label we will get.
but if we run **multi-label**, it seems not work due to we will get more than one label.

How to modify it? 
thanks

**Comment by yangarbiter** [comment]
I see, I think it can be change to the following (on line 34):
```
return yy[np.random.choice(np.arange(len(yy)), 1)[0]]
```

I will fix this bug in later version.

Thanks for reporting the bug.
