### ISSUE TITLE
Errors installing libact in Windows with Anaconda

### ISSUE THREAD

**Issue by leebanmorgan** [ntucllab/libact#179]
I'm using Anaconda and pip install. I have installed the windows C++ thing and Lapacke, and have found the lapacke.h file in my computer! But for some reason when installing it fails and says it couldn't fine the lapacke.h file! I've spent my entire day trying to figure this out.

I would be fine with not using the functions that need lapacke, but I visited this page: https://github.com/ntucllab/libact/#installation-options and I cant figure out how to set those variables to zero. When I do it in anaconda prompt I get an error message. Please help, I need to get something done with this package by tmrw night

See the attached error message

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\21mor\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"'; __file__='"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\21mor\AppData\Local\Temp\pip-wheel-oasf6hyg'
       cwd: C:\Users\21mor\AppData\Local\Temp\pip-install-5iwg9ffd\libact\
  Complete output (68 lines):
  Platform Detection: Linux. Link to liblapacke...
  Build VarianceReduction...
  Build HintSVM...
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\libact
  copying libact\__init__.py -> build\lib.win-amd64-3.7\libact
  creating build\lib.win-amd64-3.7\libact\base
  copying libact\base\dataset.py -> build\lib.win-amd64-3.7\libact\base
  copying libact\base\interfaces.py -> build\lib.win-amd64-3.7\libact\base
  copying libact\base\__init__.py -> build\lib.win-amd64-3.7\libact\base
  creating build\lib.win-amd64-3.7\libact\models
  copying libact\models\logistic_regression.py -> build\lib.win-amd64-3.7\libact\models
  copying libact\models\perceptron.py -> build\lib.win-amd64-3.7\libact\models
  copying libact\models\sklearn_adapter.py -> build\lib.win-amd64-3.7\libact\models
  copying libact\models\svm.py -> build\lib.win-amd64-3.7\libact\models
  copying libact\models\__init__.py -> build\lib.win-amd64-3.7\libact\models
  creating build\lib.win-amd64-3.7\libact\models\multilabel
  copying libact\models\multilabel\binary_relevance.py -> build\lib.win-amd64-3.7\libact\models\multilabel
  copying libact\models\multilabel\dummy_clf.py -> build\lib.win-amd64-3.7\libact\models\multilabel
  copying libact\models\multilabel\__init__.py -> build\lib.win-amd64-3.7\libact\models\multilabel
  creating build\lib.win-amd64-3.7\libact\labelers
  copying libact\labelers\ideal_labeler.py -> build\lib.win-amd64-3.7\libact\labelers
  copying libact\labelers\interactive_labeler.py -> build\lib.win-amd64-3.7\libact\labelers
  copying libact\labelers\__init__.py -> build\lib.win-amd64-3.7\libact\labelers
  creating build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\active_learning_by_learning.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\density_weighted_meta.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\density_weighted_uncertainty_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\hintsvm.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\query_by_committee.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\quire.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\random_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\uncertainty_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\variance_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies
  copying libact\query_strategies\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies
  creating build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\adaptive_active_learning.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\binary_minimization.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\cost_sensitive_reference_pair_encoding.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\maximum_margin_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\multilabel_with_auxiliary_learner.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  copying libact\query_strategies\multilabel\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
  creating build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\active_learning_with_cost_embedding.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\expected_error_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\hierarchical_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\mdsp.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  copying libact\query_strategies\multiclass\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
  creating build\lib.win-amd64-3.7\libact\utils
  copying libact\utils\__init__.py -> build\lib.win-amd64-3.7\libact\utils
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  building 'libact.query_strategies._variance_reduction' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\libact
  creating build\temp.win-amd64-3.7\Release\libact\query_strategies
  creating build\temp.win-amd64-3.7\Release\libact\query_strategies\src
  creating build\temp.win-amd64-3.7\Release\libact\query_strategies\src\variance_reduction
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\21mor\Anaconda3\lib\site-packages\numpy\core\include -I/usr/include/ -IC:\Users\21mor\Anaconda3\include -IC:\Users\21mor\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.7\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11
  cl : Command line warning D9002 : ignoring unknown option '-std=c11'
  variance_reduction.c
  libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\21mor\Anaconda3\lib\site-packages\numpy\core\include -I/usr/include/ -IC:\Users\21mor\Anaconda3\include -IC:\Users\21mor\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.7\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for libact
  Running setup.py clean for libact
Failed to build libact
Installing collected packages: libact
    Running setup.py install for libact ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\21mor\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"'; __file__='"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\21mor\AppData\Local\Temp\pip-record-67f50wqt\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\21mor\Anaconda3\Include\libact'
         cwd: C:\Users\21mor\AppData\Local\Temp\pip-install-5iwg9ffd\libact\
    Complete output (68 lines):
    Platform Detection: Linux. Link to liblapacke...
    Build VarianceReduction...
    Build HintSVM...
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\libact
    copying libact\__init__.py -> build\lib.win-amd64-3.7\libact
    creating build\lib.win-amd64-3.7\libact\base
    copying libact\base\dataset.py -> build\lib.win-amd64-3.7\libact\base
    copying libact\base\interfaces.py -> build\lib.win-amd64-3.7\libact\base
    copying libact\base\__init__.py -> build\lib.win-amd64-3.7\libact\base
    creating build\lib.win-amd64-3.7\libact\models
    copying libact\models\logistic_regression.py -> build\lib.win-amd64-3.7\libact\models
    copying libact\models\perceptron.py -> build\lib.win-amd64-3.7\libact\models
    copying libact\models\sklearn_adapter.py -> build\lib.win-amd64-3.7\libact\models
    copying libact\models\svm.py -> build\lib.win-amd64-3.7\libact\models
    copying libact\models\__init__.py -> build\lib.win-amd64-3.7\libact\models
    creating build\lib.win-amd64-3.7\libact\models\multilabel
    copying libact\models\multilabel\binary_relevance.py -> build\lib.win-amd64-3.7\libact\models\multilabel
    copying libact\models\multilabel\dummy_clf.py -> build\lib.win-amd64-3.7\libact\models\multilabel
    copying libact\models\multilabel\__init__.py -> build\lib.win-amd64-3.7\libact\models\multilabel
    creating build\lib.win-amd64-3.7\libact\labelers
    copying libact\labelers\ideal_labeler.py -> build\lib.win-amd64-3.7\libact\labelers
    copying libact\labelers\interactive_labeler.py -> build\lib.win-amd64-3.7\libact\labelers
    copying libact\labelers\__init__.py -> build\lib.win-amd64-3.7\libact\labelers
    creating build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\active_learning_by_learning.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\density_weighted_meta.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\density_weighted_uncertainty_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\hintsvm.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\query_by_committee.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\quire.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\random_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\uncertainty_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\variance_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies
    copying libact\query_strategies\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies
    creating build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\adaptive_active_learning.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\binary_minimization.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\cost_sensitive_reference_pair_encoding.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\maximum_margin_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\multilabel_with_auxiliary_learner.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel
    copying libact\query_strategies\multilabel\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies\multilabel    creating build\lib.win-amd64-3.7\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\active_learning_with_cost_embedding.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\expected_error_reduction.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\hierarchical_sampling.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\mdsp.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass
    copying libact\query_strategies\multiclass\__init__.py -> build\lib.win-amd64-3.7\libact\query_strategies\multiclass    creating build\lib.win-amd64-3.7\libact\utils
    copying libact\utils\__init__.py -> build\lib.win-amd64-3.7\libact\utils
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'libact.query_strategies._variance_reduction' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\libact
    creating build\temp.win-amd64-3.7\Release\libact\query_strategies
    creating build\temp.win-amd64-3.7\Release\libact\query_strategies\src
    creating build\temp.win-amd64-3.7\Release\libact\query_strategies\src\variance_reduction
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\21mor\Anaconda3\lib\site-packages\numpy\core\include -I/usr/include/ -IC:\Users\21mor\Anaconda3\include -IC:\Users\21mor\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.7\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11
    cl : Command line warning D9002 : ignoring unknown option '-std=c11'
    variance_reduction.c
    libact/query_strategies/src/variance_reduction/variance_reduction.c(5): fatal error C1083: Cannot open include file: 'lapacke.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\21mor\Anaconda3\lib\site-packages\numpy\core\include -I/usr/include/ -IC:\Users\21mor\Anaconda3\include -IC:\Users\21mor\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tclibact/query_strategies/src/variance_reduction/variance_reduction.c /Fobuild\temp.win-amd64-3.7\Release\libact/query_strategies/src/variance_reduction/variance_reduction.obj -std=c11" failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\21mor\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"'; __file__='"'"'C:\\Users\\21mor\\AppData\\Local\\Temp\\pip-install-5iwg9ffd\\libact\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\21mor\AppData\Local\Temp\pip-record-67f50wqt\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\21mor\Anaconda3\Include\libact' Check the logs for full command output.

**Comment by yangarbiter** [comment]
Can you try the following commands?

```
export LIBACT_BUILD_VARIANCE_REDUCTION=0
export LIBACT_BUILD_HINTSVM=0
pip install libact
```

**Comment by leebanmorgan** [comment]
I just tried that but it didn't work. I think export only works for linux? I did set instead and it worked on Windows though, thanks!
