### ISSUE TITLE
Hierarchical clustering

### ISSUE THREAD

**Issue by QajikHakobyan** [ntucllab/libact#185]
Got an assertion error, while doing query and update in herarchical clustering.
`y = []
for idx in range(len(y_pool)):
    if idx in seed_set:
        y += [y_pool[idx]]
    else:
        y += [None]
dataset = Dataset(X_pool, y)

sub_qs = UncertaintySampling(
    dataset, method='sm', model=libact.models.LogisticRegression(max_iter=1000))
qs = HierarchicalSampling(
        dataset, # Dataset object
        np.unique(y_pool),
        active_selecting=True,
        subsample_qs=sub_qs
    )

for idx in range(100):
    a = qs.make_query()
    qs.update(a, y_pool[a])
    qs.sub_qs.update(a, y_pool[a])

`

![query_update](https://user-images.githubusercontent.com/66563232/117667728-3c5faf00-b1b6-11eb-9aeb-0e8c4d0866b4.png)

**Comment by yangarbiter** [comment]
@sian-chen  Could you answer this question?

Thanks.

**Comment by QajikHakobyan** [comment]
@sian-chen  Could you please provide an working example with hierarchical sampling

**Comment by ariapoy** [comment]
> @sian-chen Could you please provide an working example with hierarchical sampling

@QajikHakobyan I write the working example and clarify this issue [here](https://nbviewer.jupyter.org/github/ariapoy/libact/blob/master/examples/libact-issue-185.ipynb).
Please check it!

Thanks.
