### ISSUE TITLE
make_query() in active_learning_by_learning is broken

### ISSUE THREAD

**Issue by joanxiao** [ntucllab/libact#35]
Hello. The make_query() method fails at the following line, with q undefined:
ask_idx = np.random.choice(
                        np.arange(len(self.unlabeled_invert_id_idx)), size=1, p=q
                    )[0]

Could you please fix it? 

Thanks!

**Comment by yangarbiter** [comment]
Hi @joanxiao 

I've made a possible fix on this problem in cb64bb1f4eb7e39b8c6ae0c657fa8cc5f6e3e1de on branch bug_fix_albl

@tungen 
Please help me double check with the bug fix
this bug appears to be started from 325fae8fbbc16b3c1ca40559bb2a9c783efaf440

Thanks.

**Comment by yangarbiter** [comment]
https://github.com/ntucllab/libact/pull/36

This problem is fixed here and merged into master.
