### ISSUE TITLE
IdealLabeler error using numpy 1.11.0b3

### ISSUE THREAD

**Issue by yangarbiter** [ntucllab/libact#37]
https://github.com/ntucllab/libact/blob/master/libact/labelers/ideal_labeler.py#L28

This line may have to be changed to 
`return self.y[np.where([np.array_equal(x, feature) for x in self.X])[0][0]]`

when using numpy 1.11.0b3

Maybe caused by this?
https://github.com/numpy/numpy/issues/6155

**Comment by tungen** [comment]
Maybe we should solve this issue after 1.11.0 is released?
