### ISSUE TITLE
Installation using pip fails for python 2

### ISSUE THREAD

**Issue by yonilx** [ntucllab/libact#55]
Tried to install libact using `sudo pip install libact` and got the following error message 
```
libact/query_strategies/variance_reduction.c:26:15: error: variable ‘moduledef’ has initializer but incomplete type
```
You can see the full error message [here](https://gist.github.com/yonilx/c969c75894b44af5ed95f38e13bd41d6).

I also tried to install using the `setup.py `script, which actually did work just fine, also the python3 installation worked using pip on the same machine.
I did some googling and the error looked similar to [here](https://github.com/syoyo/tinyobjloader/issues/54), I cant look into it because `setup.py` worked. 
Just wanted to let you guys know.

**Comment by yangarbiter** [comment]
Since we haven't issue a new release to Pypi repository
You may install it through pip install git+https://github.com/ntucllab/libact.git

**Comment by yangarbiter** [comment]
I've uploaded version v0.1.2 to pypi repository https://pypi.python.org/pypi/libact/0.1.2

you should install it with ```pip install libact``` in python2 now.
