### ISSUE TITLE
Error when installing libact

### ISSUE THREAD

**Issue by ChaoYue0307** [ntucllab/libact#96]
On Ubuntu 
When installing libact using command " pip install git+https://github.com/ntucllab/libact.git"
Get error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Q9a2LI-build/

**Comment by yangarbiter** [comment]
Is it the same error as this one?
http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c
